# -*- coding: utf-8 -*-
"""GitHubAction_Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LzJZykCNYvh47gu7WnYmr0WGKZJey9nY
"""

a = 2 + 5
b = 3

print(a*b)